[build]
  # Build script output folder
  publish = "build/"

  # ESLint can't throw any warnings or Netlify will abort the build.
  # The 'netlify-build' script will allow building on Netlify, even with warnings
